### ISSUE TITLE
fit the teminal to the board

### ISSUE THREAD

**Issue by ran632** [ran632/2048-for-linux#4]

**Comment by sagidayan** [comment]
Do you still want it to happen?

**Comment by sagidayan** [comment]
@ran632

**Comment by sagidayan** [comment]
Lets wait till the end of this semester. And ill fix this thing. Ok?

**Comment by ran632** [comment]
feel free to make any additional features. im done with it i think

2015-03-30 11:02 GMT+03:00 Sagi Dayan notifications@github.com:

> Lets wait till the end of this semester. And ill fix this thing. Ok?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ran632/2048-for-linux/issues/4#issuecomment-87583983.

## 

_רן גלילי_
-    054-8000-632*
